### ISSUE TITLE
403 when node-gyp tries to download file

### ISSUE THREAD

**Issue by carstenbaumhoegger** [jshor/symbology#16]
hey!
I wanted to try out your library, because it should fit my needs perfectly.

When I run `npm install symbology --save`, `node-gyp` fails to download v1.2.3 from AWS with a HTTP-error 403.

Here's the error:
```
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(403): https://symbologyjs.s3-us-west-2.amazonaws.com/symbology/v1.2.3/Release/symbology-v1.2.3-node-v64-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for symbology@1.2.3 and node@10.15.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
```

Is there anything I can do to get this lib working for me?

**Comment by john-doherty** [comment]
@jshor if you can explain the fix, I'll try to resolve it and submit a PR.

**Comment by jshor** [comment]
Sorry that this has been stagnating for so long. There appears to be three separate issues:

1. the S3 bucket hosting the builds had incorrect permissions
2. Travis is only building `node-pre-gyp` builds for one platform (Linux)
3. `--fallback-to-build` is failing (on Windows), will investigate on my mac soon

I'm working on it

**Comment by jshor** [comment]
Update: I've managed to get it to compile on Windows locally. Apparently there were features (mostly related to dynamic memory allocation) which were compatible with gcc but not MSVC, hence the Windows failures.

Those changes include:

* converting all the dynamic allocations to use `malloc()`
* adding `#define NO_PNG` to exclude the libpng dependency (see [zint/zint#18](https://github.com/zint/zint/issues/18)) -- libpng isn't needed anyway since we take the bitmap plot and generate a PNG from it
* fixed the signatures of the `read()` and `pipe()` methods, which apparently have a subtle difference on the MSVC compiler (they return `int` instead of `size_t`) 

For Windows users, `--fallback-to-build` should now work, provided you ensure the following:

1. that `node-gyp` isn't installed globally, as it will conflict with the local installation (run `npm remove node-gyp`)
2. that you have the MSVC compiler installed (see this [stackoverflow answer](https://stackoverflow.com/a/53344318)):

```
npm install --global --production --vs2015 windows-build-tools
npm config set msvs_version 2015 --global
```

As for downloading the win32 binary straight from S3: I set up an appveyor instance to build and publish the binary. It builds and publishes, but when I download it, I get an error telling me that it's not a valid win32 application. It's likely due to a difference in arch, or maybe node version. I'm still investigating that.

Will provide an update soon for macOS and Linux

**Comment by john-doherty** [comment]
Hi @jshor any update on the mac/linux fix?

**Comment by Ks89** [comment]
Same issue on macOS

**Comment by jshor** [comment]
A new release is on the way which will support Windows (x86 and x64), macOS, and Linux on Node.js 10+.

Development changes:

* Updated library to use [nan](https://github.com/nodejs/nan) for bindings to make the library stable for future V8 versions/Node.js releases
* Implemented smoke tests to ensure the lib builds and runs properly on each OS
* Implemented fallback mode for failing binary downloads and clarified docs on how to use

Devops changes:

* The wrapper will now clone stable versions of Zint directly and apply needed patches to adapt to Symbology.js -- this will keep the library stable
* Leveraging GitHub releases to host the binaries
* Leveraging AppVeyor to build for Windows and Travis for macOS and Linux
* CI builds for each Node.js version (10, 11, 12, 13).

Next stable release should be ready today

**Comment by jshor** [comment]
Symbology v1.7.0 is now released and supports Windows (x86/x64), Linux, and macOS on Node.js 10+.
