### ISSUE TITLE
npm i  Failed

### ISSUE THREAD

**Issue by jpf0318** [jshor/symbology#2]
Failed at the symbology@1.0.6 install script 'node-pre-gyp install --fallback-to-build'.

**Comment by asbaker** [comment]
I was having issues too. Turns out I had to `brew install gd`

**Comment by ThenmozhiD** [comment]
which version of node-pre-gyp works with this?

Throws Error as:
npm ERR! symbology@1.0.6 install: `node-pre-gyp install --fallback-to-build`

**Comment by JesusMarlor** [comment]
error to install with npm.
node-pre-gyp ERR! Tried to download: https://symbologyjs.s3-us-west-1.amazonaws.com/symbology/v1.0.6/Release/symbology-v1.0.6-node-v48-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for symbology@1.0.6 and node@6.11.0 (node-v48 ABI) (falling back to source compile with node-gyp)

**Comment by jshor** [comment]
Sorry for the late update to this. It's fixed in v1.0.7 now.

To compile the module, you'll need to have [libpng](http://www.libpng.org/pub/png/libpng.html) installed, which is why `brew install gd` worked for @asbaker.

If `node-pre-gyp` compilation fails it should fallback to a prebuilt version that I host on an AWS S3 bucket. I published a new one and updated the version, so installation should succeed now.
